### ISSUE TITLE
Excited states stuck at zero in cartpole example

### ISSUE THREAD

**Issue by wardnath** [Saran-nns/sorn#18] opened 2021-07-12 13:45 UTC
Hi there, I'm playing around with the cartpole example as a "hello-world" with sorn. I've made some modifications to optimize output weights based on CMA-ES: https://github.com/CMA-ES/pycma

In my code example however, it seems like the vector of excited states is always stuck at zero, so the agent always takes the same action regardless of the output weights.

I am wondering if I didn't initialize the network correctly, or if the `time_steps` needs to be set to >1 so that the input signal can propagate through the network.

Here is my code: 
``` python3
from sorn import Simulator, Trainer
import gym
import pickle
import numpy as np
import cma
# Load the simulated network matrices
# Note these matrices are obtained after the network achieved convergence under random inputs and noise

#with open('simulation_matrices.pkl','rb') as f:  
#    sim_matrices,excit_states,inhib_states,recur_states,num_reservoir_conn = pickle.load(f)

# Training parameters

NUM_EPISODES = int(2e6)
NUM_PLASTICITY_EPISODES = 20000

env = gym.make('CartPole-v0')
action_space = env.action_space
import pdb

output_layer_weights = np.random.uniform(-1,1,(200,1))
es = cma.CMAEvolutionStrategy(output_layer_weights,1)
#pdb.set_trace()
# Policy
def policy(state,w):
    "Implementation of softmax policy"
    z = state.dot(w)
    exp = np.exp(z)
    output = exp/np.sum(exp)
    return output

max_reward = 0
state = env.reset()[None,:]
# Note: I don't have a pre-loaded pkl file, so I am using this line to initialize
sim_matrices_init, excit_states_init, inhib_states_init, recur_states_init, num_reservoir_conn_init = Simulator.simulate_sorn(inputs = state, phase ='plasticity', time_steps = 1, noise=False, _nu=1) 

for EPISODE in range(NUM_EPISODES):
    
    # Environment observation
    state = env.reset()[None,:]
    # Play the episode
    sim_matrices = sim_matrices_init
    
    solutions = es.ask()
    reward_vector = []
    for sol_idx in range(0,19):
      output_layer_weights = solutions[sol_idx]
      while True:
        #print("Running")
        if EPISODE < NUM_PLASTICITY_EPISODES:
          # Plasticity phase
          sim_matrices, excit_states, inhib_states, recur_states, num_reservoir_conn = Simulator.simulate_sorn(inputs = state, phase ='plasticity', matrices = sim_matrices, time_steps = 1, noise=False)
        else:
          # Training phase with frozen reservoir connectivity
          sim_matrices,excit_states,inhib_states,recur_states,num_reservoir_conn = Trainer.train_sorn(inputs = state, phase = 'training', matrices = sim_matrices, noise= False)
        
        # Feed excit_states as input states to your RL algorithm, below goes for simple policy gradient algorithm
        # Sample policy w.r.t excitatory states and take action in the environment
        print(excit_states)
        probs = policy(np.asarray(excit_states),output_layer_weights)
        prob = probs[0]
        diff_probs = [prob,1-prob]
        print(diff_probs)
        action = np.random.choice(range(0,action_space.n),p=diff_probs)
        state,reward,done,_ = env.step(action) 
        state = state[None,:] 
        if done:
          reward_vector.append(reward)
          max_reward = np.max([max_reward, reward])
          print("max reward", max_reward)
          break

    # end of Iteration
    es.tell(solutions,reward_vector)

```

Here is some sample output:

```
$ python sorn_test.py 
/home/gluser/anaconda3/envs/freqtrade-conda/lib/python3.8/site-packages/cma/utilities/utils.py:343: UserWarning: input x0 should be a list or 1-D array, trying to flatten (200, 1)-array ()
  warnings.warn(msg + ' (' +
(9_w,19)-aCMA-ES (mu_w=5.6,w_1=29%) in dimension 200 (seed=143495, Mon Jul 12 13:44:22 2021)
Network Initialized
Number of connections in Wee 3922 , Wei 1590, Wie 8000
Shapes Wee (200, 200) Wei (40, 200) Wie (200, 40)
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]
[1.0, 0.0]
[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]
[1.0, 0.0]
...
```

**Comment by Saran-nns** [comment] 2021-07-12 14:17
Thanks for the issue. Could you please provide me the network parameters at config.ini file? This is common when we use the network of size 200. Network learn the structure slowly since the learning rate of stdp is relatively small. Please also try small values for network size ```ne```.

**Comment by wardnath** [comment] 2021-07-12 14:31
```
[Network_Config]

# Number of neurons in the reservoir
Ne = 200

# Number of input units in the reservoir
Nu = 10

# Connection/Network type: Sparse or Dense

network_type_ee = Sparse
network_type_ei = Sparse
network_type_ie = Dense

# Mean number of incoming and outgoing connections per neuron
lambda_ee = 20
lambda_ei = 40
lambda_ie = 100

# Hebbian Learning rate 
eta_stdp = 0.004

# Anti-Hebbian learning rate
eta_inhib = 0.001

# Intrinsic plasticity constants    
eta_ip = 0.01

# Threshold initialization values
te_max = 1.0
ti_max = 0.5
ti_min = 0.0
te_min = 0.0

# Mean and standard deviation of target firing rate , h_ip
mu_ip = 0.1
sigma_ip = 0.0 
```

The config.ini should be the same as what is on the development branch as of now, I will try reducing the size of the network and see if that works. 

Are there any other best practices for initializing the network? Should I be calling class method `initialize_weight_matrix` or `initialize_threshold_matrix` since I'm not loading weights from a pkl file like in your example?

`initialize_weight_matrix` -> https://github.com/Saran-nns/sorn/blob/master/sorn/sorn.py#L89
`initialize_threshold_matrix` -> https://github.com/Saran-nns/sorn/blob/master/sorn/sorn.py#L122

**Comment by Saran-nns** [comment] 2021-07-12 17:02
In your code, you have initialized the ```_nu``` as 1. Since cart pole env has 4 variables, you could set ```nu``` >= 4.
The initialization problem in SORN is less explored. But you could still use the helper util functions and experiment with different initialization schemes.   A sample run of your script is at colab link [here](https://colab.research.google.com/drive/1Yp3t1KRGMeOGYa-FycjP5kE1sD7CuorE#scrollTo=an7tbGsTDeHD). Hope this helps

**Comment by Saran-nns** [comment] 2021-07-12 19:23
The issue is an initialization problem. With the given example of the cart pole problem, the input size ```_nu``` has to be set according to its env variable size which is 4. Also suggested to reduce the network size ```ne```. Tested the code [here](https://colab.research.google.com/drive/1Yp3t1KRGMeOGYa-FycjP5kE1sD7CuorE#scrollTo=an7tbGsTDeHD) with ```ne = 50``` and verified the states are not stuck anymore. 

Hope it helps :)

@wardnath I am closing the issue for now. Please feel free to create new issue for more info :)

**Closed as completed by Saran-nns** 2021-07-12 19:23 UTC
Labels: question

**Comment by wardnath** [comment] 2021-07-12 20:40
Thanks @Saran-nns! This is very helpful.
